/**
 * This program is free software, you can redistribute it and/or modify it.
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file fused_sparse_attention_overlap_template_tiling_key.h
 * \brief
 */

#ifndef FUSED_SPARSE_ATTENTION_OVERLAP_TEMPLATE_TILING_KEY_H
#define FUSED_SPARSE_ATTENTION_OVERLAP_TEMPLATE_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND 0
#define FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND 1
#define FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_PA_BSND 2

#define ASCENDC_TPL_4_BW 4

#define C_TEMPLATE 0
#define V_TEMPLATE 1

// 模板参数支持的范围定�?
ASCENDC_TPL_ARGS_DECL(FusedSparseAttentionOverlap, // 算子OpType
ASCENDC_TPL_BOOL_DECL(FLASH_DECODE, 0, 1),
ASCENDC_TPL_UINT_DECL(LAYOUT_T, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND),
ASCENDC_TPL_UINT_DECL(KV_LAYOUT_T, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND,
                      FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_PA_BSND),
ASCENDC_TPL_UINT_DECL(TEMPLATE_MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, C_TEMPLATE, V_TEMPLATE),
);

// 支持的模板参数组�?
// 用于调用GET_TPL_TILING_KEY获取TilingKey时，接口内部校验TilingKey是否合法
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
    ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND),
    ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_PA_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND),
    ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, C_TEMPLATE),
    ),

    ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
    ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND),
    ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_PA_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND),
    ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, V_TEMPLATE), // V模板不支持非PA
    ),
);

#endif // FUSED_SPARSE_ATTENTION_OVERLAP_TEMPLATE_TILING_KEY_H
